=== TowoLabs/ftso-signal-providers/providerlist.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/TowoLabs/ftso-signal-providers/blob/master/providerlist.schema.json",
  "title": "Bifrost Wallet FTSO Provider List",
  "description": "Schema for lists of FTSO providers compatible with Bifrost Wallet",
  "definitions": {
    "Version": {
      "type": "object",
      "description": "The version of the list, used in change detection",
      "examples": [
        {
          "major": 2,
          "minor": 3,
          "patch": 0
        }
      ],
      "additionalProperties": false,
      "properties": {
        "major": {
          "type": "integer",
          "description": "The major version of the list. Must be incremented when FTSO providers are removed from the list or FTSO provider addresses are changed.",
          "minimum": 0,
          "examples": [
            1,
            2
          ]
        },
        "minor": {
          "type": "integer",
          "description": "The minor version of the list. Must be incremented when FTSO providers are added to the list.",
          "minimum": 0,
          "examples": [
            0,
            1
          ]
        },
        "patch": {
          "type": "integer",
          "description": "The patch version of the list. Must be incremented for any changes to the list.",
          "minimum": 0,
          "examples": [
            0,
            1
          ]
        }
      },
      "required": [
        "major",
        "minor",
        "patch"
      ]
    },
    "ProviderInfo": {
      "type": "object",
      "description": "Metadata for a single FTSO provider in a provider list",
      "additionalProperties": false,
      "properties": {
        "chainId": {
          "type": "integer",
          "description": "The chain ID of either Coston, Coston2, Flare or Songbird where this FTSO provider is submitting prices",
          "enum": [
            19,
            114,
            16,
            14
          ],
          "examples": [
            19,
            114,
            16,
            14
          ]
        },
        "name": {
          "type": "string",
          "description": "The name of the FTSO provider",
          "minLength": 2,
          "maxLength": 32,
          "pattern": "^[ \\w.'+\\-%/À-ÖØ-öø-ÿ:&\\[\\]\\(\\)]+$",
          "examples": [
            "Bifrost Oracle"
          ]
        },
        "description": {
          "type": "string",
          "description": "The description of the FTSO provider",
          "minLength": 10,
          "maxLength": 350,
          "pattern": "^[ \\w.'+\\-%/À-ÖØ-öø-ÿ:&\\[\\]\\(\\)]+",
          "examples": [
            "Bifrost Oracle"
          ]
        },
        "url": {
          "type": "string",
          "description": "A URI to the FTSO provider website. Must use HTTPS",
          "format": "uri",
          "maxLength": 100,
          "pattern": "^https://[A-Za-z0-9\/#.-]*[^/]$",
          "examples": [
            "https://bifrostoracle.com"
          ]
        },
        "address": {
          "type": "string",
          "description": "The checksummed address of the FTSO provider on the specified chain ID",
          "pattern": "^0x[a-fA-F0-9]{40}$",
          "examples": [
            "0x69141E890F3a79cd2CFf552c0B71508bE23712dC"
          ]
        },
        "logoURI": {
          "type": "string",
          "description": "A content URL for this repository to the FTSO provider logo asset",
          "pattern": "^https:\\/\\/raw\\.githubusercontent\\.com\\/TowoLabs\\/ftso-signal-providers\\/master\\/assets\\/0x[a-fA-F0-9]{40}\\.png$",
          "examples": [
            "https://raw.githubusercontent.com/TowoLabs/ftso-signal-providers/master/assets/0x69141E890F3a79cd2CFf552c0B71508bE23712dC.png"
          ]
        },
        "listed": {
          "type": "boolean",
          "description": "Specifices whether the provider meets the extended requirements to be listed in Bifrost Wallet",
          "examples": [
            "true"
          ]
        }
      },
      "required": [
        "chainId",
        "name",
        "description",
        "url",
        "address",
        "logoURI"
      ]
    }
  },
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the FTSO provider list",
      "minLength": 1,
      "maxLength": 30,
      "pattern": "^[A-Za-z ]+$",
      "examples": [
        "My Provider List"
      ]
    },
    "timestamp": {
      "type": "string",
      "format": "date-time",
      "description": "The timestamp of this list version; i.e. when this immutable version of the list was created"
    },
    "version": {
      "$ref": "#/definitions/Version"
    },
    "providers": {
      "type": "array",
      "description": "The list of providers included in the list",
      "uniqueItems": true,
      "items": {
        "$ref": "#/definitions/ProviderInfo"
      },
      "minItems": 1,
      "maxItems": 10000
    }
  },
  "required": [
    "name",
    "timestamp",
    "version",
    "providers"
  ]
}

=== TowoLabs/ftso-signal-providers/bifrost-wallet.providerlist.json
{
  "name": "Bifrost Wallet FTSO Provider List",
  "timestamp": "2026-04-09T00:00:00+00:00",
  "version": {
    "major": 7,
    "minor": 1,
    "patch": 0
  },
  "providers": [
    {
      "chainId": 19,
      "name": "Bifrost Wallet",
      "description": "Bifrost Wallet runs a competitive, accurate and reliable oracle service since 2021. Developed by Towo Labs a Songbird Network development partner.",
      "url": "https://bifrostwallet.com",
      "address": "0x69141E890F3a79cd2CFf552c0B71508bE23712dC",
      "logoURI": "https://raw.githubusercontent.com/TowoLabs/ftso-signal-providers/master/assets/0x69141E890F3a79cd2CFf552c0B71508bE23712dC.png",
      "listed": true
    },
    {
      "chainId": 14,
      "name": "Bifrost Wallet",
      "description": "Bifrost Wallet runs a competitive, accurate and reliable oracle service since 2021. Developed by Towo Labs a Flare Network development partner.",
      "url": "https://bifrostwallet.com",
      "address": "0x9A46864A3b0a7805B266C445289C3fAD1E48f18e",
      "logoURI": "https://raw.githubusercontent.com/TowoLabs/ftso-signal-providers/master/assets/0x9A46864A3b0a7805B266C445289C3fAD1E48f18e.png",
      "listed": true
    },
    {
      "chainId": 19,
      "name": "ScandiNodes FTSO",
      "description": "We are proud to be part of Flare Networks. We have a responsibility and take our role as a signal provider very serious. We do not only provide data estimates. We provide good estimates, for maximum returns.",
      "url": "https://ftso.scandinodes.com",
      "address": "0x4ed9e5b82CE66311Ac2230D2FCCc5202D7B8c083",
      "logoURI": "https://raw.githubusercontent.com/TowoLabs/ftso-signal-providers/master/assets/0x4ed9e5b82CE66311Ac2230D2FCCc5202D7B8c083.png"
    },
    {
      "chainId": 14,
      "name": "ScandiNodes FTSO",
      "description": "We are proud to be part of Flare Networks. We have a responsibility and take our role as a signal provider very serious. We do not only provide data estimates. We provide good estimates, for maximum returns.",
      "url": "https://ftso.scandinodes.com",
      "address": "0xB6d771E1892EB2c04b136C13Abe23390022e8206",
      "logoURI": "https://raw.githubusercontent.com/TowoLabs/ftso-signal-providers/master/assets/0xB6d771E1892EB2c04b136C13Abe23390022e8206.png"
    },
    {
      "chainId": 19,
      "name": "Aureus Ox",
      "description": "Aureus Ox is building a scalable and reliable FTSO signal provider. Our initial goals include accurate price submission and delegation tools.",
      "url": "https://aureusox.com",
      "address": "0x6d323e71E141cE2d7b752313C8A654a9C9d1b377",
      "logoURI": "https://raw.githubusercontent.com/TowoLabs/ftso-signal-providers/master/assets/0x6d323e71E141cE2d7b752313C8A654a9C9d1b377.png",
      "listed": true
    },
    {
      "chainId": 14,
      "name": "Aureus Ox",
      "description": "Aureus Ox is building a scalable and reliable FTSO signal provider. Our initial goals include accurate price submission and delegation tools.",
      "url": "https://aureusox.com",
      "address": "0x9269fb79B098AB314de8A1E2AFb8705678520443",
      "logoURI": "https://raw.githubusercontent.com/TowoLabs/ftso-signal-providers/master/assets/0x9269fb79B098AB314de8A1E2AFb8705678520443.png",
      "listed": true
    },
    {
      "chainId": 19,
      "name": "AlphaOracle",
      "description": "AlphaOracle is a US based Signal Provider to the Flare Network. Our goal is to provide reliable data to support applications and expand the ecosystem.",
      "url": "https://www.alphaoracle.io",
      "address": "0xBF61Db1CDb43d196309824473fA82E5B17581159",
      "logoURI": "https://raw.githubusercontent.com/TowoLabs/ftso-signal-providers/master/assets/0xBF61Db1CDb43d196309824473fA82E5B17581159.png",
      "listed": true
    },
    {
      "chainId": 14,
      "name": "AlphaOracle",
      "description": "AlphaOracle is a US based Signal Provider to the Flare Network. Our goal is to provide reliable data to support applications and expand the ecosystem.",
      "url": "https://www.alphaoracle.io",
      "address": "0x47B6EfFE71ABD4e8CdCC56f2341BEb404f804b87",
      "logoURI": "https://raw.githubusercontent.com/TowoLabs/ftso-signal-providers/master/assets/0x47B6EfFE71ABD4e8CdCC56f2341BEb404f804b87.png",
      "listed": true
    },
    {
      "chainId": 19,
      "name": "FTSO EU",
      "description": "Ftso.eu is one of the oldest signal providers building on Flare, with a strong community and presence. Our signals are weighted, dynamic, resilient, processed with an innovative approach on a distributed P2P network to guarantee their accuracy.",
      "url": "https://www.ftso.eu",
      "address": "0x010a16c53F33E4d93892f00897965578b55a8CFC",
      "logoURI": "https://raw.githubusercontent.com/TowoLabs/ftso-signal-providers/master/assets/0x010a16c53F33E4d93892f00897965578b55a8CFC.png",
      "listed": true
    },
    {
      "chainId": 14,
      "name": "FTSO EU",
      "description": "Ftso.eu is one of the oldest signal providers building on Flare, with a strong community and presence. Our signals are weighted, dynamic, resilient and processed with an innovative approach on a distributed P2P network to guarantee their accuracy.",
      "url": "https://www.ftso.eu",
      "address": "0xb0421af2cFfB21D8a0Be4087448146E4f9cbD306",
      "logoURI": "https://raw.githubusercontent.com/TowoLabs/ftso-signal-providers/master/assets/0xb0421af2cFfB21D8a0Be4087448146E4f9cbD306.png",
      "listed": true
    },
    {
      "chainId": 19,
      "name": "FTSO UK",
      "description": "Signal provider on the Flare Network. UK-based team with global coverage. Providing robust and weighted signals. Dedicated to unlocking value.",
      "url": "https://www.ftso.uk",
      "address": "0xB9b7355f5b71CEE345311921D247b1D2bA5cFe90",
      "logoURI": "https://raw.githubusercontent.com/TowoLabs/ftso-signal-providers/master/assets/0xB9b7355f5b71CEE345311921D247b1D2bA5cFe90.png"
    },
    {
      "chainId": 14,
      "name": "FTSO UK",
      "description": "Signal provider on the Flare Network. UK-based team with global coverage. Providing robust and weighted signals. Dedicated to unlocking value.",
      "url": "https://www.ftso.uk",
      "address": "0x5F911C2C681f678e5A3a8D54f950d6b192CC16E3",
      "logoURI": "https://raw.githubusercontent.com/TowoLabs/ftso-signal-providers/master/assets/0x5F911C2C681f678e5A3a8D54f950d6b192CC16E3.png"
    },
    {
      "chainId": 19,
      "name": "AU",
      "description": "AU provide accurate and reliable price feeds to the Flare Network and a transparent, incentivised, risk-free delegation service. We do so by leveraging the distributed nature of the network and its participants.",
      "url": "https://www.au.cc",
      "address": "0x499017ADB21D6f70480E4E6224cf4144071C1461",
      "logoURI": "https://raw.githubusercontent.com/TowoLabs/ftso-signal-providers/master/assets/0x499017ADB21D6f70480E4E6224cf4144071C1461.png",
      "listed": true
    },
    {
      "chainId": 14,
      "name": "AU",
      "description": "AU provide accurate and reliable price feeds to the Flare Network and a transparent, incentivised, risk-free delegation service. We do so by leveraging the distributed nature of the network and its participants.",
      "url": "https://www.au.cc",
      "address": "0x4990320858AE3528B645C60059281a66C3488888",
      "logoURI": "https://raw.githubusercontent.com/TowoLabs/ftso-signal-providers/master/assets/0x4990320858AE3528B645C60059281a66C3488888.png",
      "listed": true
    },
    {
      "chainId": 19,
      "name": "Use Your Spark",
      "description": "Global Signal Provider for the Flare Time Series Oracle (FTSO), offering vote delegation services to Songbird (SGB) token holders. Start earning risk-free rewards today!",
      "url": "https://www.useyourspark.com",
      "address": "0x53CAEDDA4339eD74272ECfEF85b657dEf18fA2e4",
      "logoURI": "https://raw.githubusercontent.com/TowoLabs/ftso-signal-providers/master/assets/0x53CAEDDA4339eD74272ECfEF85b657dEf18fA2e4.png",
      "listed": true
    },
    {
      "chainId": 14,
      "name": "Use Your Spark",
      "description": "Global Signal Provider for the Flare Time Series Oracle (FTSO), offering vote delegation services to Spark (FLR) token holders. Start earning risk-free rewards today!",
      "url": "https://www.useyourspark.com",
      "address": "0xa288054b230DCbb8689Ac229D6DBd7Df39203181",
      "logoURI": "https://raw.githubusercontent.com/TowoLabs/ftso-signal-providers/master/assets/0xa288054b230DCbb8689Ac229D6DBd7Df39203181.png",
      "listed": true
    },
    {
      "chainId": 19,
      "name": "Sun-Dara",
      "description": "Sun-Dara is an Asian STSO provider based primarily in Bangladesh with connections to the United Kingdom. We try and keep things simple and easy to understand. Check out our website for more information and service status updates.",
      "url": "https://sun-dara.co.uk",
      "address": "0x7394923453FC2F606cfb4D0ea1A5438BB8260D08",
      "logoURI": "https://raw.githubusercontent.com/TowoLabs/ftso-signal-providers/master/assets/0x7394923453FC2F606cfb4D0ea1A5438BB8260D08.png",
      "listed": true
    },
    {
      "chainId": 14,
      "name": "Sun-Dara",
      "description": "Sun-Dara is an Asian FTSO provider based primarily in Bangladesh with connections to the United Kingdom. We try and keep things simple and easy to understand. Check out our website for more information and service status updates.",
      "url": "https://sun-dara.co.uk",
      "address": "0x1E8F916CE03F4ce86186531a8994d366581Ed4be",
      "logoURI": "https://raw.githubusercontent.com/TowoLabs/ftso-signal-providers/master/assets/0x1E8F916CE03F4ce86186531a8994d366581Ed4be.png",
      "listed": true
    },
    {
      "chainId": 19,
      "name": "Lena Instruments",
      "description": "Institutional grade vote delegation service and FTSO signal provider to the Songbird ecosystem",
      "url": "https://www.lena.tech",
